wifi_ssid: "Homeboy"
wifi_password: "xyz98789#"
api_key: "f7vjvAVnP68OISC6NXWSfz5DdNQCUSQFuT3kknD8BGk="
ota_password: "sunsynk-ota-2026"
mqtt_broker: "192.168.0.50"  # TODO: Replace with your Docker host IP
